/** 운영 관리 화면은 한국어 업무 화면이다 (AGENTS.md 1절). 고객 번역 카탈로그와 분리한다. */
export const ADMIN_LABELS = {
  hub: "운영 관리",
  hotels: "호텔 관리",
  routes: "노선 판매 설정",
  readOnly: "조회 전용 권한입니다. 변경은 admin만 할 수 있습니다.",
  loadFailed: "목록을 불러오지 못했습니다.",
  empty: "등록된 항목이 없습니다.",
  status: { draft: "초안", active: "판매 노출", suspended: "일시 중지", archived: "보관" },
  route: { hotel_to_airport: "숙소 → 공항", airport_to_hotel: "공항 → 숙소", hotel_to_hotel: "숙소 → 숙소" },
  enabled: "판매 중",
  disabled: "판매 안 함",
  saveFailed: "저장하지 못했습니다. 입력값과 권한을 확인하세요.",
  conflict: "같은 slug 또는 같은 이름·주소의 호텔이 이미 있습니다.",
  create: {
    title: "호텔 지점 등록",
    zone: "권역",
    slug: "URL 식별자 (영문 소문자·숫자·하이픈)",
    nameKo: "한국어 원명",
    addressKo: "한국어 주소",
    opensAt: "프런트 인계 시작 (한국 시간)",
    closesAt: "프런트 인계 종료 (한국 시간)",
    nameZh: "중국어 간체 이름",
    aliasesZh: "중국어 별칭 (쉼표로 구분)",
    nameEn: "영어 이름",
    submit: "초안으로 등록",
    created: "초안으로 등록했습니다. 확인 후 ‘판매 노출’로 바꾸세요.",
  },
} as const;
