"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { adminFetch } from "./admin-fetch";

type Zone = { id: string; code: string; name_ko: string; status: string; display_names: Record<string, string> };
type Offering = { id: string; route_type: string; origin: { name_ko: string } | null; destination: { name_ko: string } | null };
type Price = { id: string; route_offering_id: string; bag_size: string; unit_amount_minor: number; valid_from: string; valid_until: string | null; status: string };
type Slot = { id: string; route_offering_id: string; service_date: string; pickup_starts_at: string; delivery_ends_at: string; status: string; capacity_buckets: { max_units: number; held_units: number; committed_units: number }[] };

const field = "min-h-11 w-full rounded-[var(--radius-button)] border border-line bg-bg px-3 text-sm";
const panel = "rounded-[var(--radius-card)] border border-line bg-card p-5 shadow-sm";

export function OperationsManager({ zones, offerings, prices, slots }: { zones: Zone[]; offerings: Offering[]; prices: Price[]; slots: Slot[] }) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const send = async (body: unknown) => {
    setBusy(true); setMessage("");
    const result = await adminFetch("/api/v1/admin/operations", "POST", body);
    setBusy(false);
    setMessage(result.ok ? "저장했습니다. 목록을 새로 불러옵니다." : result.code === "CONFLICT" ? "같은 기간의 규칙·슬롯이 있거나 중복 코드입니다." : result.code === "VALIDATION_FAILED" ? "입력값 또는 예약된 용량을 확인해 주세요." : "저장하지 못했습니다.");
    if (result.ok) router.refresh();
  };
  const text = (form: FormData, key: string) => String(form.get(key) ?? "").trim();
  const instant = (form: FormData, key: string) => new Date(`${text(form, key)}:00+09:00`).toISOString();
  const offeringName = (id: string) => { const route = offerings.find((row) => row.id === id); return route ? `${route.origin?.name_ko ?? "?"} → ${route.destination?.name_ko ?? "?"} · ${route.route_type}` : id; };
  const routeOptions = offerings.map((route) => <option key={route.id} value={route.id}>{offeringName(route.id)}</option>);

  return <div className="grid gap-8">
    {message ? <p role="status" className="rounded-xl border border-line bg-card px-4 py-3 text-sm">{message}</p> : null}
    <section className="grid gap-4 lg:grid-cols-[minmax(0,1.25fr)_minmax(300px,.75fr)]">
      <div className={panel}><h2 className="mb-4 text-lg font-bold">서비스 권역</h2><div className="grid gap-2">{zones.map((zone) => <div key={zone.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-line py-2 last:border-0"><div><strong>{zone.name_ko}</strong><span className="ml-2 text-xs text-muted">{zone.code} · {zone.display_names?.["zh-CN"] || "중국어 미입력"}</span></div><select aria-label={`${zone.name_ko} 상태`} className={`${field} w-auto`} disabled={busy} value={zone.status} onChange={(e) => void send({ kind: "zoneStatus", id: zone.id, status: e.target.value })}><option value="draft">초안</option><option value="active">운영</option><option value="suspended">중지</option><option value="archived">보관</option></select></div>)}</div></div>
      <form className={panel} onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void send({ kind: "zone", code: text(f, "code"), nameKo: text(f, "nameKo"), nameZh: text(f, "nameZh"), nameEn: text(f, "nameEn"), sortOrder: Number(text(f, "sortOrder") || 0) }); }}><h2 className="mb-4 text-lg font-bold">새 권역</h2><div className="grid gap-3"><label className="text-sm">코드<input required name="code" pattern="[a-z0-9][a-z0-9-]*" className={field} /></label><label className="text-sm">한국어 이름<input required name="nameKo" className={field} /></label><label className="text-sm">简体中文<input name="nameZh" lang="zh-Hans" className={field} /></label><label className="text-sm">English<input name="nameEn" lang="en" className={field} /></label><label className="text-sm">표시 순서<input name="sortOrder" type="number" min="0" defaultValue="0" className={field} /></label><button disabled={busy} className="min-h-11 rounded-[var(--radius-button)] bg-primary px-4 font-semibold text-on-primary">초안 만들기</button></div></form>
    </section>
    <section className="grid gap-4 lg:grid-cols-[minmax(0,1.25fr)_minmax(300px,.75fr)]">
      <div className={panel}><h2 className="mb-4 text-lg font-bold">요금 규칙</h2><p className="mb-3 text-sm text-muted">기존 규칙은 종료일을 정한 뒤 새 기간을 만듭니다. 겹치는 기간은 DB가 차단합니다.</p><div className="grid gap-2">{prices.map((price) => <div key={price.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-line py-2 last:border-0"><div><strong>{price.unit_amount_minor.toLocaleString()}원</strong><span className="ml-2 text-xs text-muted">{price.bag_size} · {price.valid_from}~{price.valid_until ?? "계속"}<br />{offeringName(price.route_offering_id)}</span></div><div className="flex flex-wrap items-center gap-2"><form className="flex items-center gap-1" onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void send({ kind: "priceRange", id: price.id, validUntil: text(f, "until") || null }); }}><input aria-label="요금 종료일" name="until" type="date" defaultValue={price.valid_until ?? ""} className={`${field} w-auto`} /><button disabled={busy} className="rounded-lg border border-line px-3 py-2 text-xs">종료일 저장</button></form><select aria-label="요금 상태" className={`${field} w-auto`} disabled={busy} value={price.status} onChange={(e) => void send({ kind: "priceStatus", id: price.id, status: e.target.value })}><option value="draft">초안</option><option value="active">운영</option><option value="suspended">중지</option><option value="archived">보관</option></select></div></div>)}</div></div>
      <form className={panel} onSubmit={(event) => { event.preventDefault(); const f = new FormData(event.currentTarget); void send({ kind: "price", routeOfferingId: text(f, "route"), bagSize: text(f, "bagSize"), amount: Number(text(f, "amount")), validFrom: text(f, "from"), validUntil: text(f, "until") || null }); }}><h2 className="mb-4 text-lg font-bold">새 요금 규칙</h2><div className="grid gap-3"><label className="text-sm">노선<select name="route" required className={field}>{routeOptions}</select></label><label className="text-sm">짐 규격<select name="bagSize" className={field}><option value="standard">보통</option><option value="large">대형</option></select></label><label className="text-sm">원화 금액<input name="amount" required type="number" min="0" step="1" className={field} /></label><label className="text-sm">시작일<input name="from" required type="date" className={field} /></label><label className="text-sm">종료일 · 선택<input name="until" type="date" className={field} /></label><button disabled={busy || offerings.length === 0} className="min-h-11 rounded-[var(--radius-button)] bg-primary px-4 font-semibold text-on-primary">초안 만들기</button></div></form>
    </section>
    <section className="grid gap-4 lg:grid-cols-[minmax(0,1.25fr)_minmax(300px,.75fr)]">
      <div className={panel}><h2 className="mb-4 text-lg font-bold">서비스 슬롯·용량</h2><div className="grid gap-2">{slots.map((slot) => { const bucket = slot.capacity_buckets?.[0]; return <div key={slot.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-line py-3 last:border-0"><div><strong>{slot.service_date}</strong><span className="ml-2 text-xs text-muted">{offeringName(slot.route_offering_id)}</span><p className="text-xs text-muted">수거 {new Date(slot.pickup_starts_at).toLocaleString("ko-KR", { timeZone: "Asia/Seoul" })} · 도착 {new Date(slot.delivery_ends_at).toLocaleString("ko-KR", { timeZone: "Asia/Seoul" })}</p><p className="text-xs">용량 {bucket ? `${bucket.held_units + bucket.committed_units} / ${bucket.max_units}` : "미설정"}</p></div><div className="flex flex-wrap items-center gap-2"><form onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void send({ kind: "capacity", slotId: slot.id, maxUnits: Number(text(f, "maxUnits")) }); }} className="flex gap-1"><input aria-label="최대 용량" name="maxUnits" type="number" min={bucket ? bucket.held_units + bucket.committed_units : 0} defaultValue={bucket?.max_units ?? 0} className={`${field} w-20`} /><button disabled={busy || !bucket} className="rounded-lg border border-line px-3 text-xs">용량 저장</button></form><select aria-label="슬롯 상태" className={`${field} w-auto`} disabled={busy || !bucket} value={slot.status} onChange={(e) => void send({ kind: "slotStatus", id: slot.id, status: e.target.value })}><option value="draft">초안</option><option value="active">운영</option><option value="suspended">중지</option><option value="archived">보관</option></select></div></div>; })}</div></div>
      <form className={panel} onSubmit={(event) => { event.preventDefault(); try { const f = new FormData(event.currentTarget); void send({ kind: "slot", routeOfferingId: text(f, "route"), serviceDate: text(f, "date"), bookingCutoffAt: instant(f, "cutoff"), pickupStartsAt: instant(f, "pickupStart"), pickupEndsAt: instant(f, "pickupEnd"), deliveryStartsAt: instant(f, "deliveryStart"), deliveryEndsAt: instant(f, "deliveryEnd"), maxUnits: Number(text(f, "maxUnits")) }); } catch { setMessage("날짜와 시간을 모두 입력해 주세요."); } }}><h2 className="mb-4 text-lg font-bold">새 슬롯</h2><p className="mb-3 text-xs text-muted">모든 시각은 한국 시간 기준입니다. 초안 생성 후 운영으로 전환하세요.</p><div className="grid gap-3"><label className="text-sm">노선<select name="route" required className={field}>{routeOptions}</select></label><label className="text-sm">서비스 날짜<input name="date" required type="date" className={field} /></label>{[["cutoff", "예약 마감"], ["pickupStart", "수거 시작"], ["pickupEnd", "수거 종료"], ["deliveryStart", "인계 시작"], ["deliveryEnd", "인계 종료"]].map(([key, label]) => <label key={key} className="text-sm">{label}<input name={key} required type="datetime-local" className={field} /></label>)}<label className="text-sm">최대 용량 단위<input name="maxUnits" required type="number" min="0" className={field} /></label><button disabled={busy || offerings.length === 0} className="min-h-11 rounded-[var(--radius-button)] bg-primary px-4 font-semibold text-on-primary">슬롯 초안 만들기</button></div></form>
    </section>
  </div>;
}
