"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { adminFetch } from "./admin-fetch";

type Partner = { id: string; name: string };
type Hotel = { id: string; name_ko: string; partner_id: string | null };
type Code = { id: string; code: string; partner_id: string; hotel_id: string; applicable_routes: string[]; valid_from: string; valid_until: string | null; status: string };
type Rule = { id: string; partner_id: string; kind: string; amount_minor: number | null; rate_bp: number | null; valid_from: string; valid_until: string | null; status: string };
const input = "min-h-11 w-full rounded-[var(--radius-button)] border border-line bg-bg px-3 text-sm";
const box = "rounded-[var(--radius-card)] border border-line bg-card p-5";

export function PartnerRulesManager({ partners, hotels, codes, rules }: { partners: Partner[]; hotels: Hotel[]; codes: Code[]; rules: Rule[] }) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [partner, setPartner] = useState(partners[0]?.id ?? "");
  const [mode, setMode] = useState<"flat_per_order" | "percent_of_total">("percent_of_total");
  const send = async (body: unknown) => { setBusy(true); setMessage(""); const result = await adminFetch("/api/v1/admin/partner-rules", "POST", body); setBusy(false); setMessage(result.ok ? "저장했습니다." : result.code === "CONFLICT" ? "같은 기간의 수수료 규칙 또는 중복 코드가 있습니다." : "저장하지 못했습니다. 값과 권한을 확인해 주세요."); if (result.ok) router.refresh(); };
  const value = (f: FormData, key: string) => String(f.get(key) ?? "").trim();
  const partnerName = (id: string) => partners.find((p) => p.id === id)?.name ?? "미확인";
  const hotelName = (id: string) => hotels.find((h) => h.id === id)?.name_ko ?? "미확인";
  const statusSelect = (kind: "codeStatus" | "commissionStatus", id: string, status: string) => <select aria-label="상태" value={status} disabled={busy} className={`${input} w-auto`} onChange={(e) => void send({ kind, id, status: e.target.value })}><option value="draft">초안</option><option value="active">운영</option><option value="suspended">중지</option><option value="archived">보관</option></select>;
  return <div className="grid gap-6">
    {message ? <p role="status" className="rounded-xl border border-line bg-card p-3 text-sm">{message}</p> : null}
    <div className="grid gap-4 lg:grid-cols-2"><form className={box} onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); void send({ kind: "code", code: value(f, "code").toUpperCase(), partnerId: partner, hotelId: value(f, "hotelId"), routes: ["hotel_to_airport", "airport_to_hotel", "hotel_to_hotel"].filter((r) => f.has(r)), validFrom: value(f, "from"), validUntil: value(f, "until") || null }); }}><h2 className="mb-4 text-lg font-bold">제휴 유입 코드</h2><div className="grid gap-3"><label className="text-sm">제휴사<select value={partner} onChange={(e) => setPartner(e.target.value)} className={input}>{partners.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-sm">지점<select name="hotelId" required className={input}>{hotels.filter((h) => h.partner_id === partner).map((h) => <option key={h.id} value={h.id}>{h.name_ko}</option>)}</select></label><label className="text-sm">코드 · 대문자·숫자 4–16자<input name="code" required minLength={4} maxLength={16} className={input} /></label><fieldset className="text-sm"><legend>적용 노선</legend>{[["hotel_to_airport", "숙소→공항"], ["airport_to_hotel", "공항→숙소"], ["hotel_to_hotel", "숙소→숙소"]].map(([id, label]) => <label key={id} className="mr-4 inline-flex items-center gap-1"><input type="checkbox" name={id} defaultChecked />{label}</label>)}</fieldset><label className="text-sm">시작일<input name="from" type="date" required className={input} /></label><label className="text-sm">종료일<input name="until" type="date" className={input} /></label><button disabled={busy || !hotels.some((h) => h.partner_id === partner)} className="min-h-11 rounded-[var(--radius-button)] bg-primary px-4 font-semibold text-on-primary">코드 초안 만들기</button></div></form>
      <form className={box} onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const amount = Number(value(f, "value")); void send({ kind: "commission", partnerId: value(f, "partnerId"), mode, amountMinor: mode === "flat_per_order" ? amount : null, rateBp: mode === "percent_of_total" ? Math.round(amount * 100) : null, validFrom: value(f, "from"), validUntil: value(f, "until") || null }); }}><h2 className="mb-4 text-lg font-bold">수수료 계약 규칙</h2><div className="grid gap-3"><label className="text-sm">제휴사<select name="partnerId" className={input}>{partners.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-sm">계산 방식<select value={mode} onChange={(e) => setMode(e.target.value as typeof mode)} className={input}><option value="percent_of_total">주문액 비율</option><option value="flat_per_order">주문당 정액</option></select></label><label className="text-sm">{mode === "flat_per_order" ? "주문당 금액 (원)" : "수수료율 (%)"}<input name="value" required type="number" min="0" max={mode === "flat_per_order" ? 10000000 : 100} step={mode === "flat_per_order" ? 1 : 0.01} className={input} /></label><label className="text-sm">시작일<input name="from" type="date" required className={input} /></label><label className="text-sm">종료일<input name="until" type="date" className={input} /></label><button disabled={busy || partners.length === 0} className="min-h-11 rounded-[var(--radius-button)] bg-primary px-4 font-semibold text-on-primary">규칙 초안 만들기</button></div></form></div>
    <section className={box}><h2 className="mb-4 text-lg font-bold">코드 목록</h2><div className="grid gap-2">{codes.map((code) => <div key={code.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-line py-2 last:border-0"><div><strong>{code.code}</strong><p className="text-xs text-muted">{partnerName(code.partner_id)} · {hotelName(code.hotel_id)} · {code.valid_from}~{code.valid_until ?? "계속"} · {code.applicable_routes.join(", ")}</p></div>{statusSelect("codeStatus", code.id, code.status)}</div>)}</div></section>
    <section className={box}><h2 className="mb-4 text-lg font-bold">수수료 규칙 목록</h2><div className="grid gap-2">{rules.map((rule) => <div key={rule.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-line py-2 last:border-0"><div><strong>{partnerName(rule.partner_id)} · {rule.kind === "flat_per_order" ? `${rule.amount_minor?.toLocaleString()}원/주문` : `${((rule.rate_bp ?? 0) / 100).toFixed(2)}%`}</strong><p className="text-xs text-muted">{rule.valid_from}~{rule.valid_until ?? "계속"}</p></div><div className="flex flex-wrap gap-2"><form className="flex gap-1" onSubmit={(e) => { e.preventDefault(); void send({ kind: "commissionEnd", id: rule.id, validUntil: value(new FormData(e.currentTarget), "until") || null }); }}><input name="until" type="date" defaultValue={rule.valid_until ?? ""} aria-label="수수료 종료일" className={`${input} w-auto`} /><button disabled={busy} className="rounded-lg border border-line px-3 text-xs">종료일 저장</button></form>{statusSelect("commissionStatus", rule.id, rule.status)}</div></div>)}</div></section>
  </div>;
}
