import type { Locale } from "@luggage/i18n";

export type RouteType = "hotel_to_airport" | "airport_to_hotel" | "hotel_to_hotel";

const ko = {
  badge: "시뮬레이션 · 실제 예약·결제·알림이 아닙니다",
  title: "전체 과정 체험하기",
  intro: "예약부터 짐을 돌려받기까지 모든 단계를 직접 눌러 보세요. 고객·호텔·기사·운영자 화면을 오가며 같은 주문이 어떻게 움직이는지 볼 수 있습니다.",
  reset: "처음부터",
  auto: "자동 진행",
  autoStop: "멈추기",
  steps: ["배송 정보", "확인·동의", "결제", "예약증"],
  routes: { hotel_to_airport: "숙소 → 공항", airport_to_hotel: "공항 → 숙소", hotel_to_hotel: "숙소 → 숙소" },
  airport: "제주공항",
  route: "배송 노선",
  hotel: "맡기는 숙소",
  arrivalHotel: "받는 숙소",
  destHotel: "도착 숙소",
  date: "날짜 (한국 시간)",
  slot: "시간대",
  pickup: "수거",
  delivery: "인계",
  bags: "짐 수량",
  standard: "보통 짐 (~28인치)",
  large: "대형 짐 (29인치~)",
  flight: "항공편명",
  flightTime: "항공편 시각 (한국 시간)",
  next: "다음",
  back: "이전",
  quote: "요금 확인",
  subtotal: "소계",
  discount: "할인",
  total: "결제 금액",
  vat: "부가세 포함",
  coupon: "쿠폰 코드",
  couponApply: "적용",
  couponOk: "쿠폰이 적용됐어요",
  couponBad: "사용할 수 없는 쿠폰입니다",
  couponHint: "첫 이용 쿠폰 WELCOME10: 10% 할인, 최대 5,000원 · 예약 1건에 쿠폰 1개",
  contact: "연락처",
  name: "이름",
  email: "이메일",
  wechat: "위챗 ID (선택)",
  contactHint: "한국 전화번호 없이 이메일이나 위챗 ID로 안내를 받아요.",
  policies: "필수 안내 동의",
  policyItems: ["짐 규격: 보통 158cm·23kg, 대형 203cm·32kg 이하 · 예약당 최대 8개", "금지 물품: 현금·귀중품·여권·고가 전자기기는 직접 휴대, 위험물·음식·생물은 맡길 수 없어요", "취소·환불: 수거 전날 20:00(한국 시간)까지 취소하면 전액 환불", "보상: 파손·분실은 짐 1개당 최대 50만 원까지 보상"],
  policyNote: "전체 내용은 서비스 안내 화면의 필수 안내에서 볼 수 있어요.",
  agree: "위 내용을 확인했습니다",
  payTitle: "결제 수단",
  methods: { wechat: "위챗페이", alipay: "알리페이", card: "해외 카드" },
  payNow: "결제하기",
  sheetTitle: "결제 확인",
  verifying: "PG 서버에서 결제 결과를 확인하는 중…",
  verifyNote: "브라우저 화면만으로 확정하지 않고 서버 확인 후 예약을 확정합니다.",
  paid: "결제 완료 · 예약 확정",
  voucher: "예약증",
  reference: "예약 번호",
  tag: "짐 태그",
  qrNote: "QR에는 짐 태그 번호만 들어 있어요. 개인정보는 없습니다.",
  handoffCode: "수령 코드",
  codeHint: "인계 장소에서 기사에게 이 코드를 보여주세요.",
  codeLater: "인계 준비가 끝나면 수령 코드가 표시됩니다.",
  roles: { customer: "고객", hotel: "호텔", driver: "기사", ops: "운영" },
  statuses: ["예약 확정", "호텔 보관", "기사 수거", "이동 중", "인계 준비", "수령 완료"],
  actions: {
    store: "태그 확인 후 보관",
    pickup: "QR 스캔·사진 촬영 후 수거",
    depart: "적재 완료 · 출발",
    arrive: "인계 장소 도착 · 수령 코드 발급",
    handoff: "수령 코드 확인 · 인계 완료",
    hotelReceive: "도착 숙소에서 짐 인수",
    airportCollect: "공항에서 고객 짐 받기",
  },
  waiting: "다음 차례",
  done: "모든 짐을 전달했어요 🎉",
  scanned: "스캔 완료",
  photo: "사진 기록",
  enterCode: "고객이 보여준 수령 코드",
  wrongCode: "코드가 맞지 않아요",
  notifTitle: "고객 알림 미리보기",
  notifChannel: "위챗 구독 메시지 · 이메일 (발송 시뮬레이션)",
  notifs: ["예약이 확정됐어요. 예약증을 확인해 주세요.", "호텔이 짐을 보관했어요.", "기사가 짐을 수거했어요. 짐마다 사진을 남겼어요.", "짐이 이동 중이에요. 차량 위치를 확인할 수 있어요.", "인계 준비 완료! 수령 코드를 보여주세요.", "모든 짐을 전달했어요. 이용해 주셔서 감사합니다."],
  delayNotif: "교통 상황으로 약 20분 늦어질 수 있어요. 도착 전에 다시 알려 드릴게요.",
  refundRequested: "취소 요청을 받았어요. 환불 승인을 기다리고 있어요.",
  refunded: "환불이 완료됐어요.",
  recoveryNotif: "다른 기기 로그인 코드",
  ops: "운영 센터",
  dispatch: "배차",
  driverName: "기사 A (예시)",
  vehicle: "차량 V-01 (예시)",
  events: "짐 기록",
  incident: "지연 보고",
  incidentLogged: "지연 사고가 기록되고 고객에게 알렸어요.",
  cancel: "취소·환불 요청",
  cancelClosed: "수거 후에는 온라인 취소가 불가합니다",
  approveRefund: "재무 환불 승인",
  refundState: { none: "없음", requested: "승인 대기", refunded: "환불 완료" },
  metrics: ["오늘 예약", "배송 중", "정시 인계율", "열린 문의"],
  mapTitle: "배송 차량 위치 (짐 자체 GPS 아님)",
  recovery: "다른 기기에서 예약 찾기",
  recoverySend: "코드 받기",
  recoveryCode: "받은 코드",
  recoveryVerify: "확인",
  recoveryOk: "이 기기에서도 예약을 볼 수 있어요.",
  kst: "한국 시간",
  sampleHotel: "예시 호텔",
  searchStay: "숙소 이름 검색",
  miniProgram: "위챗 미니프로그램에서는 결제 페이지로 이동해 같은 방식으로 결제해요.",
};

type Copy = typeof ko;

const zh: Copy = {
  badge: "模拟演示 · 非真实预约、付款或通知",
  title: "完整流程体验",
  intro: "从预约到取回行李，每一步都可以亲自点击体验。切换顾客、酒店、司机、运营视角，查看同一订单的流转。",
  reset: "重新开始",
  auto: "自动演示",
  autoStop: "暂停",
  steps: ["配送信息", "确认与同意", "付款", "预约凭证"],
  routes: { hotel_to_airport: "住宿 → 机场", airport_to_hotel: "机场 → 住宿", hotel_to_hotel: "住宿 → 住宿" },
  airport: "济州机场",
  route: "配送路线",
  hotel: "寄存住宿",
  arrivalHotel: "收件住宿",
  destHotel: "目的住宿",
  date: "日期（韩国时间）",
  slot: "时段",
  pickup: "取件",
  delivery: "交付",
  bags: "行李数量",
  standard: "普通行李（~28寸）",
  large: "大件行李（29寸~）",
  flight: "航班号",
  flightTime: "航班时间（韩国时间）",
  next: "下一步",
  back: "上一步",
  quote: "确认价格",
  subtotal: "小计",
  discount: "优惠",
  total: "应付金额",
  vat: "含增值税",
  coupon: "优惠码",
  couponApply: "使用",
  couponOk: "优惠码已生效",
  couponBad: "该优惠码不可用",
  couponHint: "首单优惠码 WELCOME10：九折，最多优惠 5,000 韩元 · 每笔预约限用 1 张",
  contact: "联系方式",
  name: "姓名",
  email: "邮箱",
  wechat: "微信号（选填）",
  contactHint: "无需韩国手机号，通过邮箱或微信接收通知。",
  policies: "必读须知",
  policyItems: ["行李规格：普通 158cm·23kg，大件 203cm·32kg 以内 · 每笔最多 8 件", "禁止物品：现金、贵重物品、护照、贵重电子产品请随身携带；危险品、食品、活体不可寄存", "取消退款：取件前一天 20:00（韩国时间）前取消全额退款", "赔偿：损坏或丢失每件最高赔偿 50 万韩元"],
  policyNote: "完整内容请查看服务介绍中的必读须知。",
  agree: "我已阅读并确认",
  payTitle: "付款方式",
  methods: { wechat: "微信支付", alipay: "支付宝", card: "境外银行卡" },
  payNow: "付款",
  sheetTitle: "确认付款",
  verifying: "正在向支付服务器确认付款结果…",
  verifyNote: "不以浏览器页面为准，服务器确认后才会确定预约。",
  paid: "付款成功 · 预约已确认",
  voucher: "预约凭证",
  reference: "预约号",
  tag: "行李标签",
  qrNote: "二维码只包含行李标签号，不含个人信息。",
  handoffCode: "取件码",
  codeHint: "在交付地点向司机出示此代码。",
  codeLater: "准备交付后将显示取件码。",
  roles: { customer: "顾客", hotel: "酒店", driver: "司机", ops: "运营" },
  statuses: ["预约确认", "酒店保管", "司机取件", "运送中", "准备交付", "已取回"],
  actions: {
    store: "核对标签后保管",
    pickup: "扫码拍照后取件",
    depart: "装车完成 · 出发",
    arrive: "到达交付地点 · 发放取件码",
    handoff: "核对取件码 · 完成交付",
    hotelReceive: "目的住宿接收行李",
    airportCollect: "在机场接收顾客行李",
  },
  waiting: "下一步由",
  done: "所有行李已送达 🎉",
  scanned: "已扫码",
  photo: "照片记录",
  enterCode: "顾客出示的取件码",
  wrongCode: "取件码不正确",
  notifTitle: "顾客通知预览",
  notifChannel: "微信订阅消息 · 邮件（模拟发送）",
  notifs: ["预约已确认，请查看预约凭证。", "酒店已保管您的行李。", "司机已取件，每件行李均已拍照记录。", "行李运送中，可查看车辆位置。", "已准备交付！请出示取件码。", "所有行李已送达，感谢使用。"],
  delayNotif: "受交通影响可能延迟约 20 分钟，到达前会再次通知您。",
  refundRequested: "已收到取消申请，正在等待退款审核。",
  refunded: "退款已完成。",
  recoveryNotif: "其他设备登录验证码",
  ops: "运营中心",
  dispatch: "派单",
  driverName: "司机 A（示例）",
  vehicle: "车辆 V-01（示例）",
  events: "行李记录",
  incident: "上报延误",
  incidentLogged: "已记录延误并通知顾客。",
  cancel: "申请取消退款",
  cancelClosed: "取件后无法在线取消",
  approveRefund: "财务审批退款",
  refundState: { none: "无", requested: "待审批", refunded: "已退款" },
  metrics: ["今日预约", "运送中", "准时交付率", "未结咨询"],
  mapTitle: "配送车辆位置（非行李本身GPS）",
  recovery: "在其他设备查找预约",
  recoverySend: "获取验证码",
  recoveryCode: "验证码",
  recoveryVerify: "确认",
  recoveryOk: "此设备也可以查看预约了。",
  kst: "韩国时间",
  sampleHotel: "示例酒店",
  searchStay: "搜索住宿名称",
  miniProgram: "在微信小程序中会跳转到付款页面，以同样方式付款。",
};

const en: Copy = {
  badge: "Simulation · Not a real booking, payment or notification",
  title: "Try the full journey",
  intro: "Tap through every step from booking to getting your bags back. Switch between guest, hotel, driver and operations views to follow the same order.",
  reset: "Start over",
  auto: "Auto play",
  autoStop: "Pause",
  steps: ["Details", "Review", "Payment", "Voucher"],
  routes: { hotel_to_airport: "Stay → Airport", airport_to_hotel: "Airport → Stay", hotel_to_hotel: "Stay → Stay" },
  airport: "Jeju Airport",
  route: "Route",
  hotel: "Drop-off stay",
  arrivalHotel: "Receiving stay",
  destHotel: "Destination stay",
  date: "Date (Korea time)",
  slot: "Time window",
  pickup: "Pickup",
  delivery: "Handoff",
  bags: "Bags",
  standard: "Standard (up to 28\")",
  large: "Large (29\"+)",
  flight: "Flight number",
  flightTime: "Flight time (Korea time)",
  next: "Next",
  back: "Back",
  quote: "Price",
  subtotal: "Subtotal",
  discount: "Discount",
  total: "Total",
  vat: "VAT included",
  coupon: "Coupon code",
  couponApply: "Apply",
  couponOk: "Coupon applied",
  couponBad: "This coupon can't be used",
  couponHint: "First-ride coupon WELCOME10: 10% off, up to KRW 5,000 · one coupon per booking",
  contact: "Contact",
  name: "Name",
  email: "Email",
  wechat: "WeChat ID (optional)",
  contactHint: "No Korean phone number needed — updates by email or WeChat.",
  policies: "Required notices",
  policyItems: ["Bag size: standard up to 158 cm / 23 kg, large up to 203 cm / 32 kg · max 8 bags", "Prohibited: keep cash, valuables, passports and electronics with you; no hazardous items, food or live animals", "Cancellation: full refund until 8:00 pm Korea time the day before pickup", "Compensation: up to KRW 500,000 per bag for damage or loss"],
  policyNote: "Read the full notices on the service guide page.",
  agree: "I have read the notices",
  payTitle: "Payment method",
  methods: { wechat: "WeChat Pay", alipay: "Alipay", card: "Card" },
  payNow: "Pay",
  sheetTitle: "Confirm payment",
  verifying: "Checking the result with the payment server…",
  verifyNote: "Bookings are confirmed only after the server verifies payment, not by the browser screen.",
  paid: "Paid · Booking confirmed",
  voucher: "Voucher",
  reference: "Booking no.",
  tag: "Bag tag",
  qrNote: "QR codes hold only the bag tag number — no personal data.",
  handoffCode: "Handoff code",
  codeHint: "Show this code to the driver at the handoff point.",
  codeLater: "Your handoff code appears once the handoff is ready.",
  roles: { customer: "Guest", hotel: "Hotel", driver: "Driver", ops: "Ops" },
  statuses: ["Confirmed", "Stored at hotel", "Picked up", "In transit", "Ready for handoff", "Delivered"],
  actions: {
    store: "Check tags & store",
    pickup: "Scan QR, photo & pick up",
    depart: "Loaded · depart",
    arrive: "Arrived · issue handoff code",
    handoff: "Verify code · complete handoff",
    hotelReceive: "Destination stay receives bags",
    airportCollect: "Collect guest bags at airport",
  },
  waiting: "Next up",
  done: "All bags delivered 🎉",
  scanned: "Scanned",
  photo: "Photo record",
  enterCode: "Code shown by guest",
  wrongCode: "Code doesn't match",
  notifTitle: "Guest notification preview",
  notifChannel: "WeChat subscription message · Email (simulated)",
  notifs: ["Your booking is confirmed. See your voucher.", "The hotel is storing your bags.", "The driver picked up your bags and photographed each one.", "Your bags are on the move. Track the vehicle.", "Ready for handoff! Show your code.", "All bags delivered. Thank you!"],
  delayNotif: "Traffic may delay us by about 20 minutes. We'll update you before arrival.",
  refundRequested: "Cancellation received. Waiting for refund approval.",
  refunded: "Your refund is complete.",
  recoveryNotif: "Sign-in code for another device",
  ops: "Operations",
  dispatch: "Dispatch",
  driverName: "Driver A (sample)",
  vehicle: "Vehicle V-01 (sample)",
  events: "Bag events",
  incident: "Report delay",
  incidentLogged: "Delay logged and guest notified.",
  cancel: "Request cancel & refund",
  cancelClosed: "Online cancellation closes after pickup",
  approveRefund: "Finance: approve refund",
  refundState: { none: "None", requested: "Awaiting approval", refunded: "Refunded" },
  metrics: ["Bookings today", "In transit", "On-time handoff", "Open tickets"],
  mapTitle: "Delivery vehicle position (not a GPS on the bag)",
  recovery: "Find booking on another device",
  recoverySend: "Get code",
  recoveryCode: "Code",
  recoveryVerify: "Verify",
  recoveryOk: "This device can now see the booking.",
  kst: "Korea time",
  sampleHotel: "Sample hotel",
  searchStay: "Search stay name",
  miniProgram: "In the WeChat Mini Program you'll pay on its payment page the same way.",
};

export const DEMO_COPY: Record<Locale, Copy> = { ko, "zh-CN": zh, en };
export type DemoCopy = Copy;
